"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import type { User } from "firebase/auth";
import { doc, getDoc, setDoc } from "firebase/firestore";
import { db } from "@/lib/firebase";
import { loginWithGoogle, logout, watchAuth } from "@/lib/auth";
import {
  addPlanningCatalogItem, createPlanningItem, ensurePlanningCatalogs, planningCatalogSelection,
  removePlanningCatalogItem, removePlanningItem, updatePlanningCatalogItem, updatePlanningItem,
  watchPlanningCatalogs, watchPlanningItems, watchProfiles,
  type PlanningCatalogItem, type PlanningCatalogType, type PlanningItem, type Profile,
} from "@/lib/firestore";

const todayIso=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`};
const money=(n:number)=>`${n<0?"−":""}$${Math.abs(n).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const LABELS:Record<PlanningCatalogType,string>={category:"Categories",nature:"Nature",relevance:"Relevance",frequency:"Frequency",status:"Status",confidence:"Confidence"};
const monthKey=(date:string)=>date.slice(0,7);

export default function PlanningPage(){
  const [user,setUser]=useState<User|null>(null),[authReady,setAuthReady]=useState(false);
  const [profiles,setProfiles]=useState<Profile[]>([]),[profileId,setProfileId]=useState<string|null>(null);
  const [items,setItems]=useState<PlanningItem[]>([]),[catalogs,setCatalogs]=useState<PlanningCatalogItem[]>([]);
  const [itemModal,setItemModal]=useState(false),[catalogModal,setCatalogModal]=useState(false),[editing,setEditing]=useState<PlanningItem|null>(null);
  const [saving,setSaving]=useState(false),[error,setError]=useState("");
  useEffect(()=>watchAuth(u=>{setUser(u);setAuthReady(true)}),[]);
  useEffect(()=>{if(!user){setProfiles([]);setProfileId(null);return}let unsub=()=>{};(async()=>{const pref=await getDoc(doc(db,"users",user.uid));const saved=pref.data()?.activeProfileId;unsub=watchProfiles(user.uid,ps=>{setProfiles(ps);setProfileId(cur=>cur&&ps.some(p=>p.id===cur)?cur:typeof saved==="string"&&ps.some(p=>p.id===saved)?saved:ps[0]?.id??null)})})().catch(e=>setError(e instanceof Error?e.message:"Could not load profiles."));return()=>unsub()},[user]);
  useEffect(()=>{if(!profileId){setItems([]);setCatalogs([]);return}ensurePlanningCatalogs(profileId).catch(console.error);const a=watchPlanningItems(profileId,setItems),b=watchPlanningCatalogs(profileId,setCatalogs);return()=>{a();b()}},[profileId]);
  const activeProfile=profiles.find(p=>p.id===profileId)??null;
  const byType=useMemo(()=>{const map={} as Record<PlanningCatalogType,PlanningCatalogItem[]>;(Object.keys(LABELS) as PlanningCatalogType[]).forEach(t=>map[t]=catalogs.filter(c=>c.catalogType===t).sort((a,b)=>a.sortOrder-b.sortOrder||a.name.localeCompare(b.name)));return map},[catalogs]);
  const activeItems=items.filter(i=>i.statusSystemKey!=="cancelled"&&i.statusSystemKey!=="completed");
  const inflows=activeItems.filter(i=>i.type==="inflow").reduce((s,i)=>s+i.estimatedAmount,0),outflows=activeItems.filter(i=>i.type==="outflow").reduce((s,i)=>s+i.estimatedAmount,0);
  const grouped=useMemo(()=>{const map=new Map<string,PlanningItem[]>();items.forEach(i=>{const k=monthKey(i.targetDate);map.set(k,[...(map.get(k)??[]),i])});return [...map.entries()].sort(([a],[b])=>a.localeCompare(b))},[items]);
  async function selectProfile(id:string){setProfileId(id);if(user)await setDoc(doc(db,"users",user.uid),{activeProfileId:id},{merge:true})}
  async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!profileId)return;const f=new FormData(e.currentTarget);const find=(t:PlanningCatalogType,id:string)=>byType[t].find(x=>x.id===id);const c=planningCatalogSelection(find("category",String(f.get("categoryId")||""))),n=planningCatalogSelection(find("nature",String(f.get("natureId")||""))),r=planningCatalogSelection(find("relevance",String(f.get("relevanceId")||""))),q=planningCatalogSelection(find("frequency",String(f.get("frequencyId")||""))),s=planningCatalogSelection(find("status",String(f.get("statusId")||""))),cf=planningCatalogSelection(find("confidence",String(f.get("confidenceId")||"")));
    const payload:Omit<PlanningItem,"id"|"profileId">={title:String(f.get("title")||"").trim(),type:String(f.get("type")) as "inflow"|"outflow",estimatedAmount:Number(f.get("estimatedAmount")),startDate:String(f.get("startDate")||"")||undefined,targetDate:String(f.get("targetDate")),note:String(f.get("note")||"").trim()||undefined,categoryId:c.id,categoryName:c.name,natureId:n.id,natureName:n.name,relevanceId:r.id,relevanceName:r.name,frequencyId:q.id,frequencyName:q.name,statusId:s.id,statusName:s.name,statusSystemKey:s.systemKey,confidenceId:cf.id,confidenceName:cf.name};
    if(!payload.title||!payload.targetDate||!Number.isFinite(payload.estimatedAmount)||payload.estimatedAmount<=0)return;try{setSaving(true);setError("");if(editing)await updatePlanningItem(profileId,editing.id,payload);else await createPlanningItem(profileId,payload);setItemModal(false);setEditing(null)}catch(err){setError(err instanceof Error?err.message:"Could not save planning item.")}finally{setSaving(false)}}
  async function addCatalog(e:FormEvent<HTMLFormElement>,type:PlanningCatalogType){e.preventDefault();if(!profileId)return;const form=e.currentTarget,name=String(new FormData(form).get("name")||"").trim();if(name){await addPlanningCatalogItem(profileId,type,name);form.reset()}}
  if(!authReady)return <main className="app-shell"><section className="expense-loading">Loading BillTrack…</section></main>;
  if(!user)return <main className="app-shell"><section className="expense-login"><div className="brandmark">✓</div><h1>BillTrack Planning</h1><p>Sign in to access your future financial plans.</p><button className="primary" onClick={()=>loginWithGoogle()}>Sign in with Google</button></section></main>;
  return <main className="app-shell">
    <header className="topbar"><div className="brand"><div className="brandmark">✓</div><div><h1>BillTrack</h1><span>See what may be coming before it becomes due.</span></div></div><div className="account-actions"><Link className="ghost nav-link" href="/">Commitments</Link><button className="ghost" onClick={()=>logout()}>Sign out</button></div></header>
    <nav className="module-nav"><Link href="/">Commitments</Link><Link href="/expenses">Expenses</Link><Link className="active" href="/planning">Planning</Link></nav>
    <section className="content expenses-content">{error&&<div className="data-error">{error}</div>}
      <div className="expense-head"><div><p className="eyebrow">PLANNING</p><h2>Expected money, before it becomes reality.</h2><p>Plan future inflows and outflows without treating estimates as bank balances or commitments.</p></div><div className="expense-actions"><button className="ghost" onClick={()=>setCatalogModal(true)}>Manage catalogs</button><button className="primary" disabled={!activeProfile} onClick={()=>{setEditing(null);setItemModal(true)}}>＋ Add plan</button></div></div>
      <div className="profiles expense-profiles">{profiles.map(p=><button key={p.id} className={`profile ${profileId===p.id?"active":""}`} onClick={()=>selectProfile(p.id)}><span>{p.initials}</span><b>{p.name}</b><small>{profileId===p.id?"Active profile":"Open profile"}</small></button>)}</div>
      {activeProfile?<><div className="expense-summary planning-summary"><div><small>PROFILE</small><strong>{activeProfile.name}</strong></div><div><small>EXPECTED INFLOWS</small><strong>{money(inflows)}</strong></div><div><small>PLANNED OUTFLOWS</small><strong>{money(outflows)}</strong></div><div><small>NET PLANNED</small><strong>{money(inflows-outflows)}</strong></div></div><p className="planning-disclaimer">Planning totals are estimates, not available cash or account balances.</p>
        <div className="expense-list-head"><div><p className="eyebrow">TIMELINE</p><h3>Future plans</h3></div></div><div className="planning-timeline">{!items.length&&<div className="empty">No plans recorded for this profile yet.</div>}{grouped.map(([month,monthItems])=><section className="planning-month" key={month}><h4>{new Date(`${month}-01T12:00:00`).toLocaleDateString("en-CA",{month:"long",year:"numeric"})}</h4>{monthItems.map(item=><article className={`expense-row planning-row ${item.type}`} key={item.id} onClick={()=>{setEditing(item);setItemModal(true)}}><div className="planning-direction">{item.type==="inflow"?"↑":"↓"}</div><div className="expense-main"><h4>{item.title}</h4><p>{[item.categoryName,item.statusName,item.confidenceName,item.frequencyName].filter(Boolean).join(" · ")||"Unclassified"}</p></div><div className="expense-meta"><small>{item.targetDate}</small><span>{item.relevanceName||item.natureName||""}</span></div><strong className="expense-amount">{money(item.estimatedAmount)}</strong><button className="delete" onClick={e=>{e.stopPropagation();if(profileId&&confirm(`Delete ${item.title}?`))removePlanningItem(profileId,item.id)}}>×</button></article>)}</section>)}</div>
      </>:<div className="empty">Create or select a profile in Commitments first.</div>}
    </section>
    {itemModal&&activeProfile&&<div className="backdrop" onMouseDown={e=>e.target===e.currentTarget&&setItemModal(false)}><div className="modal expense-modal"><button className="close" onClick={()=>setItemModal(false)}>×</button><p className="eyebrow">{activeProfile.name.toUpperCase()}</p><h3>{editing?"Edit plan":"Add plan"}</h3><form onSubmit={save}><label>Title<input name="title" required placeholder="Vacation, tuition, OSAP, vehicle sale…" defaultValue={editing?.title??""}/></label><div className="grid2"><label>Direction<select name="type" defaultValue={editing?.type??"outflow"}><option value="outflow">Outflow — money going out</option><option value="inflow">Inflow — money coming in</option></select></label><label>Estimated amount<input name="estimatedAmount" type="number" min="0.01" step="0.01" required defaultValue={editing?.estimatedAmount??""}/></label></div><div className="grid2"><label>Start date <small>(optional)</small><input name="startDate" type="date" defaultValue={editing?.startDate??""}/></label><label>Target date<input name="targetDate" type="date" required defaultValue={editing?.targetDate??todayIso()}/></label></div><PlanSelect label="Category" name="categoryId" items={byType.category} value={editing?.categoryId}/><div className="grid2"><PlanSelect label="Nature" name="natureId" items={byType.nature} value={editing?.natureId}/><PlanSelect label="Relevance" name="relevanceId" items={byType.relevance} value={editing?.relevanceId}/></div><div className="grid2"><PlanSelect label="Frequency" name="frequencyId" items={byType.frequency} value={editing?.frequencyId}/><PlanSelect label="Confidence" name="confidenceId" items={byType.confidence} value={editing?.confidenceId}/></div><PlanSelect label="Status" name="statusId" items={byType.status} value={editing?.statusId}/><label>Note <small>(optional)</small><textarea name="note" rows={3} defaultValue={editing?.note??""}/></label><button className="primary full" disabled={saving}>{saving?"Saving…":editing?"Save changes":"Save plan"}</button></form></div></div>}
    {catalogModal&&activeProfile&&<div className="backdrop" onMouseDown={e=>e.target===e.currentTarget&&setCatalogModal(false)}><div className="modal catalog-modal"><button className="close" onClick={()=>setCatalogModal(false)}>×</button><p className="eyebrow">{activeProfile.name.toUpperCase()}</p><h3>Planning catalogs</h3><p className="catalog-intro">These planning options belong to this profile and can evolve with your needs.</p><div className="catalog-groups">{(Object.keys(LABELS) as PlanningCatalogType[]).map(type=><section className="catalog-group" key={type}><h4>{LABELS[type]}</h4><form className="catalog-add" onSubmit={e=>addCatalog(e,type)}><input name="name" placeholder={`Add ${LABELS[type].toLowerCase()}`}/><button className="ghost">＋ Add</button></form><div>{byType[type].map(item=><PlanCatalogRow key={item.id} item={item} profileId={activeProfile.id}/>)}</div></section>)}</div></div></div>}
  </main>
}
function PlanSelect({label,name,items,value}:{label:string;name:string;items:PlanningCatalogItem[];value?:string}){const active=items.filter(x=>x.active||x.id===value);return <label>{label}<select name={name} defaultValue={value??""}><option value="">Not specified</option>{active.map(i=><option key={i.id} value={i.id}>{i.name}{!i.active?" (inactive)":""}</option>)}</select></label>}
function PlanCatalogRow({item,profileId}:{item:PlanningCatalogItem;profileId:string}){const [name,setName]=useState(item.name);useEffect(()=>setName(item.name),[item.name]);return <div className={`catalog-row ${item.active?"":"inactive"}`}><input value={name} onChange={e=>setName(e.target.value)} onBlur={()=>name.trim()&&name.trim()!==item.name&&updatePlanningCatalogItem(profileId,item.id,{name})}/><button className="catalog-toggle" onClick={()=>updatePlanningCatalogItem(profileId,item.id,{active:!item.active})}>{item.active?"Active":"Inactive"}</button><button className="delete" onClick={()=>confirm(`Remove ${item.name}? Existing plans keep their saved label.`)&&removePlanningCatalogItem(profileId,item.id)}>×</button></div>}
